AllCops:
  Exclude:
    - 'vendor/**/*'
    - '**/*.gemspec'

Lint/HandleExceptions:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Max: 2

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AlignParameters:
  Enabled: false

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Style/TrailingComma:
  EnforcedStyleForMultiline: 'comma'

Style/SingleLineBlockParams:
  Enabled: false

Style/WordArray:
  Enabled: false
